alias l='ls -la'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias open='xdg-open'
alias vsc='visual-studio-code'
alias weather='curl wttr.in/hague,netherlands'
alias reddit='rtv'
alias v='nvim'
alias 'cd..'='cd_up'
alias andaga='node index.js'
