alias l='ls -la'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias weather='curl wttr.in/hague,netherlands'
alias reddit='rtv'
alias v='nvim'
alias vsun="nvim --cmd 'let sunny=1'"
alias 'cd..'='cd_up'
alias andaga='node index.js'
alias new-sbt='sbt new scala/scala-seed.g8'
alias flux-on='flux -l 52 -g 4'
alias kcrs='keybase chat read sekipp'
alias kcss='keybase chat send sekipp'
