alias l='ls -la'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias weather='curl wttr.in/hague,netherlands'
alias v='nvim'
alias 'cd..'='cd_up'
alias andaga='node index.js'
alias new-sbt='sbt new scala/scala-seed.g8'
alias mlog='tail -f .metals/metals.log'
