eval %sh{kak-lsp --kakoune -s $kak_session}

hook global WinSetOption filetype=(scala) %{
  lsp-enable-window
  set global lsp_server_configuration metals.superMethodLenses=true
}

hook global BufCreate .*[.](sbt) %{
        set-option buffer filetype scala
}

lsp-auto-hover-enable
set global lsp_hover_anchor true

set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

